### ISSUE TITLE
太强了，8.14M的压缩为12.5M

### ISSUE THREAD

**Issue by danuo2011** [iamlinhui/pdf-helper#2]

**Comment by iamlinhui** [comment]
pdf压缩 能腾出的空间只有字体格式  再就是压缩图片 图片压缩比例选的不大的话  会有图片因为压缩格式转换会导致文件变大  效果明显 就是控制在0.25以内

**Comment by danuo2011** [comment]
那如何做才能做到压缩那，本身我的文档是有图片的

**Comment by iamlinhui** [comment]
调整压缩比例  也就是对每张图片的压缩  或者自己实现解析pdf 分解其中的图片 针对图片压缩后再替换原图还原为pdf文件
